name = "newsnow-project"  # 你的项目名称
type = "javascript"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow_db"  # 替换为你创建的数据库名称
database_id = "77ef4f8e-b695-4c79-9426-56d483e335eb"      # 替换为你创建的数据库 ID
